set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# GNU Arm toolchain prefix
set(TOOLCHAIN_PREFIX "arm-none-eabi" CACHE STRING "GNU Arm toolchain prefix")

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++ CACHE FILEPATH "C++ compiler")
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc CACHE FILEPATH "ASM compiler")
set(CMAKE_AR ${TOOLCHAIN_PREFIX}-ar CACHE FILEPATH "Archiver")
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy CACHE FILEPATH "Objcopy")
set(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}-objdump CACHE FILEPATH "Objdump")
